name: Unit test for EC-CUBE
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'
env:
  PLUGIN_NAME: DataMigration4
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php: [ 7.4 ]
        db: [ mysql, pgsql ]
        include:
          - db: mysql
            database_url: mysql://root:password@127.0.0.1:3306/eccube_db
            database_server_version: 5
          - db: pgsql
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 11

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Clone EC-CUBE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            tar cvzf $HOME/${PLUGIN_NAME}.tar.gz ./*
            git clone  https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/EC-CUBE/ec-cube.git -b ${{ matrix.eccube-versions }} --depth=1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: composer install
        run: |
          sudo composer selfupdate --1
          composer install --dev --no-interaction -o --apcu-autoloader
          composer require pear/pear-core-minimal:^1.10.0alpha2
          composer require pear/archive_tar:^1.4.3
          composer require wapmorgan/unified-archive:^0.0.3
          composer require nobuhiko/bulk-insert-query

      - name: Setup EC-CUBE
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          run: |
            cd ec-cube
            bin/console doctrine:database:create
            bin/console doctrine:schema:create
            bin/console eccube:fixtures:load

      - name: Install Plugin
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          run: |
            cd ec-cube
            bin/console eccube:plugin:install --path=$HOME/${PLUGIN_NAME}.tar.gz
            bin/console cache:clear --no-warmup
            bin/console eccube:plugin:enable --code=${PLUGIN_NAME}

      - name: PHPUnit
        env:
          APP_ENV: 'test'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          MAILER_URL: 'smtp://localhost:1025'
        run: |
          cd ec-cube
          bin/phpunit -c app/Plugin/{$PLUGIN_NAME}/phpunit.xml.dist app/Plugin/{$PLUGIN_NAME}/Tests/
